spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: swamesha444@gmail.com
    password: wpcw ktet luvh ocrd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true